export enum ActionTypes {
    CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD',
    REQUEST_ROBOTS_PENDING = 'REQUETS_ROBOTS_PENDIG',
    REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS',
    REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED'
}